const products = [
    { id: 1, name: "Robe Africaine Pagne", category: "Femme", subcategory: "Robes", price: 45000, oldPrice: 55000, img: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop", badge: "sale" },
    { id: 2, name: "Robe Soirée Élégante", category: "Femme", subcategory: "Robes", price: 55000, oldPrice: 0, img: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=500&fit=crop", badge: "new" },
    { id: 3, name: "Robe Portefeuille", category: "Femme", subcategory: "Robes", price: 32000, oldPrice: 38000, img: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&h=500&fit=crop", badge: "sale" },
    { id: 4, name: "Jupe Longue élégante", category: "Femme", subcategory: "Jupes", price: 19000, oldPrice: 0, img: "jupes (1).jpg", badge: "new" },
    { id: 6, name: "Jupe tendance", category: "Femme", subcategory: "Jupes", price: 20000, oldPrice: 20000, img: "jupes (2).jpg", badge: "sale" },
    { id: 7, name: "T-Shirt oversize", category: "Femme", subcategory: "Hauts", price: 22000, oldPrice: 0, img: "hautfemme (1).jpg", badge: "" },
    { id: 8, name: "T-Shirt imprimé", category: "Femme", subcategory: "Hauts", price: 18000, oldPrice: 0, img: "hautfemme (2).jpg", badge: "new" },
    { id: 9, name: "T-Shirt crop top", category: "Femme", subcategory: "Hauts", price: 15000, oldPrice: 0, img: "hautfemme (3).jpg", badge: "" },
    { id: 10, name: "Ensemble Tailleur", category: "Femme", subcategory: "Ensembles", price: 65000, oldPrice: 80000, img: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400&h=500&fit=crop", badge: "sale" },
    { id: 11, name: "Ensemble Jupe & Haut", category: "Femme", subcategory: "Ensembles", price: 35000, oldPrice: 0, img: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&h=500&fit=crop", badge: "" },
    { id: 12, name: "Pagne Bazin Riche", category: "Femme", subcategory: "Pagnes", price: 35000, oldPrice: 0, img: "pagne (1).jpg", badge: "" },
    { id: 13, name: "Pagne Tissu Hollandais", category: "Femme", subcategory: "Pagnes", price: 55000, oldPrice: 65000, img: "pagne (2).jpg", badge: "sale" },
    { id: 14, name: "Pagne Wax Coton", category: "Femme", subcategory: "Pagnes", price: 25000, oldPrice: 0, img: "pagne (3).jpg", badge: "" },
    { id: 15, name: "Sac à Main Cuir", category: "Femme", subcategory: "Accessoires", price: 28000, oldPrice: 35000, img: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=500&fit=crop", badge: "sale" },
    { id: 16, name: "Foulard Soie", category: "Femme", subcategory: "Accessoires", price: 12000, oldPrice: 0, img: "accfemme (2).jpg", badge: "" },
    { id: 17, name: "Collier Perles", category: "Femme", subcategory: "Accessoires", price: 8500, oldPrice: 12000, img: "acfemme (7).jpg", badge: "sale" },
    { id: 18, name: "Boucles d'Oreilles", category: "Femme", subcategory: "Accessoires", price: 15000, oldPrice: 0, img: "acfemme (6).jpg", badge: "new" },
    { id: 19, name: "Chaussures Talon", category: "Femme", subcategory: "Chaussures", price: 32000, oldPrice: 0, img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop", badge: "new" },
    { id: 20, name: "Sandales Plat", category: "Femme", subcategory: "Chaussures", price: 15000, oldPrice: 0, img: "acfemme (5).jpg", badge: "" },
    { id: 21, name: "Baskets Femme", category: "Femme", subcategory: "Chaussures", price: 25000, oldPrice: 30000, img: "acfemme (4).jpg", badge: "sale" },
    { id: 22, name: "Pantalon Taille Basse", category: "Femme", subcategory: "Pantalons", price: 20000, oldPrice: 0, img: "acfemme (2).jpg", badge: "" },
    { id: 23, name: "Jean Slim Femme", category: "Femme", subcategory: "Pantalons", price: 22000, oldPrice: 0, img: "acfemme(9).jpg", badge: "" },
    { id: 24, name: "Tunique Africaine", category: "Femme", subcategory: "Robes", price: 20000, oldPrice: 0, img: "acfemme (1).jpg", badge: "" },
    { id: 25, name: "Ceinture Femme", category: "Femme", subcategory: "Accessoires", price: 10000, oldPrice: 0, img: "acfemme (8).jpg", badge: "" },
    { id: 26, name: "Jupe crayon", category: "Femme", subcategory: "Jupes", price: 20000, oldPrice: 23000, img: "jupes (3).jpg", badge: "sale" },
    { id: 27, name: "Jupe Plissée", category: "Femme", subcategory: "Jupes", price: 20000, oldPrice: 25000, img: "jupes (4).jpg", badge: "sale" },
    { id: 28, name: "T-Shirt basique", category: "Femme", subcategory: "Hauts", price: 15000, oldPrice: 0, img: "hautfemme (4).jpg", badge: "" },
    { id: 29, name: "Costume Complet", category: "Homme", subcategory: "Costumes", price: 100000, oldPrice: 150000, img: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=500&fit=crop", badge: "sale" },
    { id: 30, name: "Costume Cravate", category: "Homme", subcategory: "Costumes", price: 95000, oldPrice: 0, img: "costume (1).jpg", badge: "new" },
    { id: 31, name: "Smoking noir", category: "Homme", subcategory: "Costumes", price: 180000, oldPrice: 0, img: "costume (2).jpg", badge: "" },
    { id: 32, name: "Costume Prince de Galles", category: "Homme", subcategory: "Costumes", price: 110000, oldPrice: 0, img: "costume (3).jpg", badge: "" },
    { id: 33, name: "Chemise Manches Longues", category: "Homme", subcategory: "Chemises", price: 20000, oldPrice: 0, img: "chemise (1).jpg", badge: "" },
    { id: 34, name: "Chemise Blanche", category: "Homme", subcategory: "Chemises", price: 18000, oldPrice: 0, img: "chemise (2).jpg", badge: "" },
    { id: 35, name: "Chemise manches courtes", category: "Homme", subcategory: "Chemises", price: 15000, oldPrice: 0, img: "chemise (3).jpg", badge: "new" },
    { id: 36, name: "Chemise Oversize", category: "Homme", subcategory: "Chemises", price: 25000, oldPrice: 0, img: "chemise (4).jpg", badge: "new" },
    { id: 37, name: "T-Shirt Balenciaga", category: "Homme", subcategory: "T-Shirts", price: 12000, oldPrice: 0, img: "T-shirthomme (1).jpg", badge: "" },
    { id: 38, name: "T-Shirt luiviton", category: "Homme", subcategory: "T-Shirts", price: 15000, oldPrice: 0, img: "T-shirthomme (2).jpg", badge: "" },
    { id: 39, name: "T-Shirt GUCCI", category: "Homme", subcategory: "T-Shirts", price: 10000, oldPrice: 0, img: "T-shirthomme (3).jpg", badge: "" },
    { id: 40, name: "T-Shirt OFF", category: "Homme", subcategory: "T-Shirts", price: 10000, oldPrice: 0, img: "T-shirthomme (4).jpg", badge: "" },
    { id: 41, name: "AMIRI-Black jeans", category: "Homme", subcategory: "Pantalons", price: 45000, oldPrice: 0, img: "pantalonhomme (1).jpg", badge: "new" },
    { id: 42, name: "Chrome Hearts jeans", category: "Homme", subcategory: "Pantalons", price: 36500, oldPrice: 50000, img: "pantalonhomme (2).jpg", badge: "sale" },
    { id: 43, name: "AMIRI Black Baggy Fit jeans", category: "Homme", subcategory: "Pantalons", price: 40000, oldPrice: 0, img: "pantalonhomme (3).jpg", badge: "" },
    { id: 44, name: "AMIRI-MX1", category: "Homme", subcategory: "Pantalons", price: 30000, oldPrice: 0, img: "pantalonhomme (4).jpg", badge: "" },
    { id: 45, name: "NIKE", category: "Homme", subcategory: "Chaussures", price: 55000, oldPrice: 0, img: "chaussureshomme (1).jpg", badge: "" },
    { id: 46, name: "NEW BALANCE", category: "Homme", subcategory: "Chaussures", price: 50000, oldPrice: 65000, img: "chaussureshomme (2).jpg", badge: "sale" },
    { id: 47, name: "NIKE", category: "Homme", subcategory: "Chaussures", price: 58000, oldPrice: 0, img: "chaussureshomme (3).jpg", badge: "" },
    { id: 48, name: "NIKE Air Force", category: "Homme", subcategory: "Chaussures", price: 58500, oldPrice: 0, img: "chaussureshomme (4).jpg", badge: "" },
    { id: 53, name: "Robe Fillette", category: "Enfant", subcategory: "Filles", price: 52000, oldPrice: 0, img: "filles (1).jpg", badge: "new" },
    { id: 54, name: "Assembles", category: "Enfant", subcategory: "Filles", price: 45000, oldPrice: 0, img: "filles (2).jpg", badge: "" },
    { id: 55, name: "Assembles", category: "Enfant", subcategory: "Filles", price: 49000, oldPrice: 0, img: "filles (3).jpg", badge: "" },
    { id: 56, name: "Robes princesses", category: "Enfant", subcategory: "Filles", price: 29000, oldPrice: 0, img: "filles (4).jpg", badge: "new" },
    { id: 57, name: "Assemble", category: "Enfant", subcategory: "Garçons", price: 28000, oldPrice: 0, img: "garcons (1).jpg", badge: "" },
    { id: 58, name: "Assemble sport", category: "Enfant", subcategory: "Garçons", price: 30000, oldPrice: 0, img: "garcons (2).jpg", badge: "" },
    { id: 59, name: "Assemble", category: "Enfant", subcategory: "Garçons", price: 25000, oldPrice: 0, img: "garcons (3).jpg", badge: "" },
    { id: 60, name: "Veste enfant", category: "Enfant", subcategory: "Garçons", price: 35000, oldPrice: 0, img: "garcons (4).jpg", badge: "" },
    { id: 61, name: "Ensemble Bébé", category: "Enfant", subcategory: "Bébés", price: 15000, oldPrice: 0, img: "bébé (1).jpg", badge: "" },
    { id: 62, name: "Ensemble Bébé", category: "Enfant", subcategory: "Bébés", price: 18000, oldPrice: 0, img: "bébé (2).jpg", badge: "new" },
    { id: 63, name: "Ensemble Bébé", category: "Enfant", subcategory: "Bébés", price: 10000, oldPrice: 0, img: "bébé (3).jpg", badge: "" },
    { id: 64, name: "Ensemble Bébé", category: "Enfant", subcategory: "Bébés", price: 16000, oldPrice: 0, img: "bébé (4).jpg", badge: "" },
    { id: 65, name: "Chaussures Enfant", category: "Enfant", subcategory: "Chaussures", price: 10000, oldPrice: 0, img: " basketkids (1).jpg", badge: "" },
    { id: 66, name: "Chaussures Enfant", category: "Enfant", subcategory: "Chaussures", price: 7000, oldPrice: 0, img: " basketkids (2).jpg", badge: "" }
];
